"""realistic schema
Revision ID: 
Revises: 
Create Date: 2026-06-25 02:44:50.965330
"""

revision = "f26b3ffeef17"

down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.add_column('appointments', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('appointments', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('appointments', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('appointments', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('appointments', 'mode',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.execute("CREATE TYPE appointmentstatusenum AS ENUM ('SCHEDULED','COMPLETED','CANCELLED');")
    op.execute("UPDATE appointments SET status = UPPER(status);")
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', name='appointmentstatusenum'),
               postgresql_using='status::appointmentstatusenum',
               existing_nullable=True)
    op.alter_column('appointments', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # Delete orphaned appointment rows with missing patient, doctor, or hospital references
    op.execute("""DELETE FROM appointments a WHERE NOT EXISTS (SELECT 1 FROM patients p WHERE p.id = a."patientId");""")
    op.execute("""DELETE FROM appointments a WHERE NOT EXISTS (SELECT 1 FROM doctors d WHERE d.id = a."doctorId");""")
    op.execute("""DELETE FROM appointments a WHERE NOT EXISTS (SELECT 1 FROM hospitals h WHERE h.id = a."hospitalId");""")
    op.create_foreign_key(None, 'appointments', 'patients', ['patientId'], ['id'])
    op.create_foreign_key(None, 'appointments', 'doctors', ['doctorId'], ['id'])
    op.create_foreign_key(None, 'appointments', 'hospitals', ['hospitalId'], ['id'])
    op.drop_column('appointments', 'patient')
    op.drop_column('appointments', 'doctor')
    op.add_column('billing', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.add_column('billing', sa.Column('status', sa.String(), nullable=True))
    op.add_column('billing', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('billing', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('billing', sa.Column('is_active', sa.Boolean(), nullable=True))
    # Create enum type for doctor specialization and normalize existing data
    op.execute("CREATE TYPE specializationenum AS ENUM ('CARDIOLOGY','NEUROLOGY','ORTHOPEDICS','GENERAL');")
    op.execute("UPDATE doctors SET specialization = UPPER(specialization);")
    # Ensure specialization enum exists and normalize
    op.execute("CREATE TYPE specializationenum AS ENUM ('CARDIOLOGY','NEUROLOGY','ORTHOPEDICS','GENERAL');")
    op.execute("UPDATE doctors SET specialization = UPPER(specialization);")
    op.alter_column('doctors', 'specialization',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('CARDIOLOGY', 'NEUROLOGY', 'ORTHOPEDICS', 'GENERAL', name='specializationenum'),
               postgresql_using='specialization::specializationenum',
               existing_nullable=True)
    op.create_foreign_key(None, 'doctors', 'hospitals', ['hospitalId'], ['id'])
    op.drop_column('doctors', 'hospitalid')
    op.add_column('hospitals', sa.Column('address', sa.String(), nullable=True))
    op.add_column('hospitals', sa.Column('city', sa.String(), nullable=True))
    op.add_column('hospitals', sa.Column('state', sa.String(), nullable=True))
    op.add_column('hospitals', sa.Column('zip_code', sa.String(), nullable=True))
    op.add_column('hospitals', sa.Column('contact_number', sa.String(), nullable=True))
    op.add_column('hospitals', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('hospitals', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('hospitals', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('patients', sa.Column('email', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('address', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    op.add_column('patients', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('patients', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('patients', sa.Column('is_active', sa.Boolean(), nullable=True))
    # Create gender enum type and normalize data
    op.execute("CREATE TYPE genderenum AS ENUM ('MALE','FEMALE','OTHER');")
    op.execute("UPDATE patients SET gender = UPPER(gender);")
    op.alter_column('patients', 'gender',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('MALE', 'FEMALE', 'OTHER', name='genderenum'),
               postgresql_using='gender::genderenum',
               existing_nullable=True)
    op.create_unique_constraint(None, 'patients', ['email'])
    op.create_foreign_key(None, 'patients', 'hospitals', ['hospitalId'], ['id'])
    op.drop_column('patients', 'hospitalid')
    op.create_foreign_key(None, 'prescriptions', 'doctors', ['doctorId'], ['id'])
    op.create_foreign_key(None, 'prescriptions', 'hospitals', ['hospitalId'], ['id'])
    op.create_foreign_key(None, 'users', 'doctors', ['doctorId'], ['id'])
    op.create_foreign_key(None, 'users', 'hospitals', ['hospitalId'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.add_column('patients', sa.Column('hospitalid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint(None, 'patients', type_='unique')
    op.alter_column('patients', 'gender',
               existing_type=sa.Enum('MALE', 'FEMALE', 'OTHER', name='genderenum'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('patients', 'is_active')
    op.drop_column('patients', 'updated_at')
    op.drop_column('patients', 'created_at')
    op.drop_column('patients', 'date_of_birth')
    op.drop_column('patients', 'address')
    op.drop_column('patients', 'phone_number')
    op.drop_column('patients', 'email')
    op.drop_column('hospitals', 'is_active')
    op.drop_column('hospitals', 'updated_at')
    op.drop_column('hospitals', 'created_at')
    op.drop_column('hospitals', 'contact_number')
    op.drop_column('hospitals', 'zip_code')
    op.drop_column('hospitals', 'state')
    op.drop_column('hospitals', 'city')
    op.drop_column('hospitals', 'address')
    op.add_column('doctors', sa.Column('hospitalid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.alter_column('doctors', 'specialization',
               existing_type=sa.Enum('CARDIOLOGY', 'NEUROLOGY', 'ORTHOPEDICS', 'GENERAL', name='specializationenum'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('billing', 'is_active')
    op.drop_column('billing', 'updated_at')
    op.drop_column('billing', 'created_at')
    op.drop_column('billing', 'status')
    op.drop_column('billing', 'paid_at')
    op.add_column('appointments', sa.Column('doctor', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('patient', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.alter_column('appointments', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('appointments', 'status',
               existing_type=sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', name='appointmentstatusenum'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('appointments', 'mode',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('appointments', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('appointments', 'is_active')
    op.drop_column('appointments', 'updated_at')
    op.drop_column('appointments', 'created_at')
    op.drop_column('appointments', 'duration_minutes')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
